### ISSUE TITLE
Some ideas on the representation, as a tech tree(full tree, and more informative about the technologies)

### ISSUE THREAD

**Issue by Depact** [milaq/sit#12]
How about more complete flowcharts?
1. The path to the selected technology from the earliest, and to the desired, with full information on of each the desired technology, without trimming information about the previous .
2. Grouping into a full tech tree, with the division into three main categories(physics,  society, engineering), and bringing in the classic tech tree as a result(I mean something like tech tree from galactic civilizations).
   2.1. Mode complete and concise information to full tech tree mode.

**Comment by milaq** [comment]
see #2
